const COUNT = "COUNT" 
const GET_CONTACTS = "GET_CONTACTS" 
const COUNT_NAV = "COUNT_NAV"
const DELETE = "DELETE"
const VIEW = "VIEW"
const GET_ALl_CONTACTS = "GET_ALl_CONTACTS"
const COUNT_PAG = "COUNT_PAG"
const CREATE = "CREATE"



export {
    GET_CONTACTS , COUNT , COUNT_NAV , DELETE , VIEW ,GET_ALl_CONTACTS ,COUNT_PAG , CREATE
}