const SHOW_ERROR_MESSAGE = "SHOW_ERROR_MESSAGE"
const SHOW_SUCCESS_MESSAGE = "SHOS_SUCCESS_MESSAGE"
const CLEAR_MESSAGE = "CLEAR_MESSAGE"


export {
    SHOW_ERROR_MESSAGE , SHOW_SUCCESS_MESSAGE , CLEAR_MESSAGE
}